language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
   - docker
   - xvfb
addons:
  sonarcloud:
    organization: "laviniadd"
install: true
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar/cache

script:
 - git fetch --unshallow
 - mvn -f progetto/pom.xml clean verify -Pdocker -Pjacoco coveralls:report sonar:sonar
