language: java
matrix:
 include:
 - jdk: openjdk8
 - jdk: openjdk9
 - os: osx
 osx_image: xcode10.1
# skip installation step
install: true
cache:
   directories:
      - $HOME/.m2
script:
- mvn -f progetto/pom.xml clean verify -Pjacoco coveralls:report