dist: trusty

language: java

jdk: openjdk8

#env: DISPLAY=:99.0

services:
   - docker
  # - xvfb
addons:
  sonarcloud:
    organization: "laviniadd"
    token: ${SONAR_TOKEN}
    
install: true
cache:
   directories:
   - $HOME/.m2
   - $HOME/.sonar/cache
before_script:
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - sleep 3 # give xvfb some time to start  
script:
 - git fetch --unshallow
 - mvn -f progetto/pom.xml clean verify -Pdocker -Pjacoco coveralls:report sonar:sonar
