language: java
matrix:
 include:
 - jdk: openjdk8
  env: ADDITIONAL_MAVEN_ARGS="-Pjacoco coveralls:report"
# - jdk: openjdk9
# - os: osx
# osx_image: xcode10.1
# skip installation step
services:
 - docker
install: true
cache:
   directories:
      - $HOME/.m2
script:
- mvn -f progetto/pom.xml clean verify $ADDITIONAL_MAVEN_ARGS
#- mvn -f progetto/pom.xml clean verify -Pjacoco
#- mvn -f progetto/pom.xml clean verify -Pdocker